---
title: "9. Error Handling"
date: 2022-11-24
author: "Jordan Schnur jordan@jordanschnur.com"
id: 20221124135950
keywords:
  - "errors"
  - "try/catch"
---

# 9. Error Handling
Rust groups #errors into two categories. 

1. **Recoverable Errors**: IE: File not found, report error, try again.
2. **Unrecoverable Errors**:  Always the symptom of a bug. IE: Index out of bounds. Stops program immediately.


## Result Type
#result
A reminder of the definition: 
```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```

In the following code, `greeting_file_result` returns a `Result<File>` 
```rust
use std::fs::File;

fn main() {
    let greeting_file_result = File::open("hello.txt");
}
```

You can deal with it by using a match
```rust
match greeting_file_result {
	Ok(File) => println!("Opened file for reading"),
	Err(e) => println!("{}", e.to_string()), 
	// You can also panic here if this was breaking:
	// Err(e) => panic!("{}", e.to_string()),
}
```

An even more robust way of capturing every scenario is using nested #match. This will attempt to create the file if it does not exist, otherwise it will panic based on creating vs reading the file.
```rust
let greeting_file = match greeting_file_result {
	Ok(file) => file,
	Err(e) => match e.kind() {
		ErrorKind::NotFound => match File::create("hello.txt") {
			Ok(Fc) => Fc,
			Err(err) => panic!("Problem creating the file: {:?}", e),
		},
		other_error => {
			panic!("Problem opening the file: {:?}", other_error)
		}
	}
};
```

To simplify the code you can use #closures and the `unwrap_or_else` method. The code becomes much simpler to read.
```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file = File::open("hello.txt").unwrap_or_else(|error| {
        if error.kind() == ErrorKind::NotFound {
            File::create("hello.txt").unwrap_or_else(|error| {
                panic!("Problem creating the file: {:?}", error);
            })
        } else {
            panic!("Problem opening the file: {:?}", error);
        }
    });
}
```

A result contains the #unwrap method, which will return the result if `Ok`, otherwise it will call the panic macro for us. You can use the #expect method to do the same thing, except you can choose the panic message. `Expect` is more common to use in Production code.

You can propagate up errors by simply returning a `Result`. This code will pass the result to the function that called it. That lets the caller deal with issues.
```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let username_file_result = File::open("hello.txt");

    let mut username_file = match username_file_result {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut username = String::new();

    match username_file.read_to_string(&mut username) {
        Ok(_) => Ok(username),
        Err(e) => Err(e),
    }
}
```

### The ? operator
A shortcut to the code above is using the #questionmark operator.
```rust
use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username_file = File::open("hello.txt")?;
    let mut username = String::new();
    username_file.read_to_string(&mut username)?;
    Ok(username)
}
```

This is close to the code above, however error values that have the `?` operator go through the #from function defined in the `From` trait in the standard library. It is used to convert one type to another. When the `?` operator calls the from function the error type received is converted into the error type defined in the return type of the current function. We could convert `read_username_from_file` to our own custom error using `impl From&lt;io::Error&gt; for OurError`, and the `from` function would our from function without us needed any more code.

You can shorten the code further 
```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let mut username = String::new();

    File::open("hello.txt")?.read_to_string(&mut username)?;

    Ok(username)
}
```

The function you use ? in must return `Option`, `Result`, or another type that implements `FromResidual`. Meaning this code will error:
```rust
use std::fs::File;

fn main() {
    let greeting_file = File::open("hello.txt")?;
}
```

Main can also return a Result using the `Box<dyn Error>` trait object. For now, understand it to mean any kind of error. 
```rust
fn main() -> Result<(), Box<dyn Error>> {
    let greeting_file_result = File::open("hello.txt")?;
    
    Ok(())
}
```


## Panic Macro
#panic
Panic can occur in two ways
1. By taking an action that causes code to panic IE: Index out of bounds
2. Explicitly calling the panic! macro

By default when a panic occurs the program prints a failure message, unwinds, cleans up the stack and exits.
> **_NOTE ℹ️:_** You can skip unwinding by adding `panic = 'abort'` to the `[profile.release]` section in your #cargotoml. This will not clean up memory and force the operating system to do so.

We can cause a program to crash by calling the `panic!` macro
```rust
fn main() {
    panic!("Crash and burn");
}
```

When trying to read an index out of bounds, Rust will panic and crash. C allows you to read data beyond an index and can result in unpredictable behavior and security issues. 
```rust
fn main() {
    let v = vec![1, 2, 3];
    v[99];
}
```

> **_NOTE ℹ️:_** You can set the `RUST_BACKTRACE` env variable to `full` to get more info from a panic. Debug symbols are enabled by default. You can use the `--release` flag  with #cargobuild or #cargorun to disable debug symbols.

## To panic! or Not to panic!
If an action of your code base causes an error in which there is no way to recover, you panic. Otherwise use results.

When using actions that could panic, such as #unwrap you are saying it is a placeholder for how your code would deal with errors.

If you have more information than the compiler, such as when you're sure logically an error could never occur it is okay to use unwrap. Even better to document it using expect.
```rust
use std::net::IpAddr;

let home: IpAddr = "127.0.0.1"
	.parse()
	.expect("Hardcoded IP address should be valid");
```

### Custom types for validation
You can create types to do validation for you. 
In this example, you can not create a `guess` unless the value is between 1 and 100. Otherwise, you would have to check for this in every function in an application that it is used.
```rust
pub struct Guess {
    value: i32,
}

impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 || value > 100 {
            panic!("Guess value must be between 1 and 100, got {}.", value);
        }

        Guess { value }
    }

    pub fn value(&self) -> i32 {
        self.value
    }
}
```

The method `value` is commonly called a #getter and ensures there is no way to set value other than the `new` associated function. Therefore, you know `Guess.value()` is always between 1 and 100 and there is no need to implement error checking for it.